import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import FooterPage from "@/components/footer/footer";
import Catalog from "@/components/catalog/catalog";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/theme/theme-provider";
import ClientClerkProvider from "@/components/provider/clerk-provider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <ClientClerkProvider>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="light"
                        enableSystem
                        disableTransitionOnChange
                    >
                        <div className="min-h-screen flex flex-col">
                            <Navbar />

                            <main className="flex flex-1 flex-col container max-w-345 mx-auto w-full mt-30">
                                <Catalog />
                                <NextTopLoader
                                    color="#ec4899"
                                    height={3}
                                    showSpinner={false}
                                    shadow="0 0 10px #ec4899, 0 0 5px #ec4899"
                                />
                                {children}
                                <Toaster />
                            </main>

                            <FooterPage />
                        </div>
                    </ThemeProvider>
                </ClientClerkProvider>
            </body>
        </html>
    );
}
